# Generated by Django 5.2.16 on 2026-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_analysis', '0002_alter_foodlabel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlabel',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
