# Generated by Django 5.2.16 on 2026-08-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_allergy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_medical_condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
